# Generated by Django 4.1 on 2022-10-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Certifications',
        ),
    ]
